language: php

sudo: false
dist: trusty
group: edge

php:
    - 7.0
    - 7.1
    - 7.2

git:
    depth: 1

cache:
    apt: true
    ccache: true
    timeout: 691200
    directories:
        - vendor
        - $HOME/.composer/cache
        - $HOME/cphalcon
        - $HOME/ext

env:
    global:
        - PHALCON_VERSION="v3.3.0"

before_install:
    - export PHP_VERSION=$(php-config --version)
    - export PHP_EXTENSION_DIR=$(php-config --extension-dir)
    - phpenv config-rm xdebug.ini || true
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com $GH_TOKEN; fi;
    - if [ ! -f "$HOME/cphalcon/tests/_ci/phalcon.ini" ]; then git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b $PHALCON_VERSION $HOME/cphalcon >/dev/null 2>&1; fi;

install:
    - if [ ! -f $HOME/ext/$PHP_VERSION/phalcon.so ]; then cd $HOME/cphalcon/build && bash ./install --phpize $(phpenv which phpize) --php-config $(phpenv which php-config) && mkdir -p $HOME/ext/$PHP_VERSION && cp $PHP_EXTENSION_DIR/phalcon.so $HOME/ext/$PHP_VERSION/phalcon.so; fi;
    - if [ -f $HOME/ext/$PHP_VERSION/phalcon.so ]; then cp $HOME/ext/$PHP_VERSION/phalcon.so $PHP_EXTENSION_DIR/phalcon.so; fi;
    - phpenv config-add $HOME/cphalcon/tests/_ci/phalcon.ini
    - phpenv config-add $TRAVIS_BUILD_DIR/tests/_ci/memcached.ini
    - cd $TRAVIS_BUILD_DIR
    - travis_retry composer install --prefer-dist --no-interaction

before_script:
    - cp ./tests/_ci/.env .env
    - php -S 127.0.0.1:8000 -t public/ .htrouter.php >/dev/null 2>&1 &

script:
    - vendor/bin/phpcs
    - vendor/bin/phpmd bootstrap text codesize,unusedcode,naming --ignore-violations-on-exit
    - vendor/bin/phpmd app text codesize,unusedcode,naming --ignore-violations-on-exit
    - vendor/bin/codecept build
    - vendor/bin/codecept run unit

notifications:
    email:
    recipients:
        - build@phalconphp.com
    on_success: change
    on_failure: always

addons:
    hosts:
        - docs.phalcon.ld
